version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8080:80'
    volumes:
      - ./src:/var/www/html/

  db:
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/blog.sql:/docker-entrypoint-initdb.d/blog.sql
